[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
clap = "4.5.3"
half = "2.4.0"
safetensors = "0.4.2"
serde = "1.0"
serde_json = "1.0"
gguf-swiss = { path = "crates/gguf-swiss" }
